export const ERROR_CODES = {
  PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND",
  AUTH_FAILED: "AUTH_FAILED",
  ORDER_NOT_FOUND: "ORDER_NOT_FOUND",
  STORE_NOT_FOUND: "STORE_NOT_FOUND",
  INSUFFICIENT_STOCK: "INSUFFICIENT_STOCK",
  UNAUTHORIZED: "UNAUTHORIZED",
  GENERAL_ERROR: "general",
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;